name: clone workflow
on: 
  workflow_dispatch:   
jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: executing
        uses: cbragger/ssh-action@master
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
              git clone git@github.com:cbragger/CMSC389T-Web-P5.git